<<<<<<< HEAD
server.port=8072
spring.application.name=book-service

spring.datasource.url=jdbc:postgresql://localhost:5432/book_db
=======
spring.application.name=book-service
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=book_service

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=book_service
>>>>>>> 4d86d0c4135e1994223e865a5ad294362675ee52
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8071/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=book-service
info.app.description=Book Service for BookStore
info.app.version=1.0.0
=======
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.port=8060

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs



>>>>>>> 4d86d0c4135e1994223e865a5ad294362675ee52
